FROM node:alpine

# USER node

WORKDIR '/app'
# RUN mkdir -p /home/node/app
# WORKDIR /home/node/app

COPY package.json .
RUN npm install
# COPY --chown=node:node ./package.json ./
# RUN --chown=node:node npm install

COPY . .
# COPY --chown=node:node ./ ./

CMD ["npm" , "run", "start"]