FROM node:16-alpine

USER node

# WORKDIR '/app'
WORKDIR /home/node/app

# COPY package.json .
COPY --chown=node:node ./package.json ./
RUN npm install

# COPY . .
COPY --chown=node:node ./ ./

CMD ["npm" , "run", "start"]